### ISSUE TITLE
Feature request: support for MADS

### ISSUE THREAD

**Issue by pawelmat** [CycoPH/atasm-altirra-bridge#1]
Good job with the extension, nice alternative to WUDSN. Can you please add support for the popular MADS assembler? I made it work by selecting a path to MADS in settings (as the alternative path to the assembler) and editing AssemblerRunner.js, as MADS has slightly different command line switches (-o: for the output file, -t: for symbols and -l: for the lst file). If would however be nice to have a choice of assemblers in settings, or at least a way to define an alternative command line for the assembler. Thanks!

**Comment by CycoPH** [comment]
Thank you for the feature request.
I guess that will not make it an atasm altirra bridge anymore :)
I'll put in the feature for you

**Comment by pawelmat** [comment]
Hi Peter,

 

Thanks! Yes I thought the same 😊 but the environment is really promising and if there is no particular reason to limit it to atasm then it would be nice to open it up. Maybe you can rename it 😊 I would gladly try to move over from Eclipse+WUDSN as I personally like VSCode, so do many other people I guess.

 

I would have maybe participated in the project but VSCode extensions are a bit of an enigma for me so I would probably cause more harm than good…

 

Cheers,

Pawel

**Comment by CycoPH** [comment]
Version 1.6 of the plugin now supports mads.
Please check it out and let me know if you need any more  changes done
