### ISSUE TITLE
Altirra does not reopen correctly when re-launching code without closing it

### ISSUE THREAD

**Issue by pawelmat** [CycoPH/atasm-altirra-bridge#2]
In the settings menu there is an option to "automatically close any existing Altirra instances before opening a new one". Despite marking it, when I leave Altirra open and select "assemble and run"  or "assemble and debug" Altirra indeed closes but I get the following error:

`Launching emulator...
"C:\Emulators\Altirra\Altirra64.exe"
/pal /run "out\myproject.xex" 
Exit code: 1`

After pressing run again it works because Altirra is already closed.
There is a /singleinstance switch in Altirra maybe that would do the job more effectively if added to the command line by default when selecting the abovementioned option.

I am using MADS if that makes any difference.

**Comment by CycoPH** [comment]
Which OS are you running on?  
Under Windows when I have "Auto Close Running Altirra" option enabled it kills the running Altirra process correctly.
Can you try the following:
- turn off "Auto Close Running Altirra"
- Add the /singleinstance option to the "Emulator > Altirra: Args" command line arguments
That should work

**Comment by pawelmat** [comment]
Windows 10. Yes the method you proposed works and that's what I've been doing instead of using the "Auto Close Running Altirra".

**Comment by CycoPH** [comment]
There is a new option to always only run Altirra with the /singleinstance flag.
