### ISSUE TITLE
Syntax highlighting does not work properly

### ISSUE THREAD

**Issue by fredlcore** [CycoPH/atasm-altirra-bridge#6]
Hi,
first of all thanks a lot for this great plugin! It really makes my life a lot easier :)!
Everything works fine except syntax highlighting which looks a bit odd:
<img width="150" alt="Bildschirmfoto 2022-08-19 um 10 38 10" src="https://user-images.githubusercontent.com/24660955/185580010-2a5750b5-aa1f-4679-a6aa-7cdfe869b740.png">
Some commands are highlighted, others are not. Do you have an explanation for that? Or is there a setting that I forgot to activate?

**Comment by CycoPH** [comment]
I’ll check that you for you.

 

From: fredlcore ***@***.***> 
Sent: Friday, 19 August 2022 10:41
To: CycoPH/atasm-altirra-bridge ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CycoPH/atasm-altirra-bridge] Syntax highlighting does not work properly (Issue #6)

 

Hi,
first of all thanks a lot for this great plugin! It really makes my life a lot easier :)!
Everything works fine except syntax highlighting which looks a bit odd:
 <https://user-images.githubusercontent.com/24660955/185580010-2a5750b5-aa1f-4679-a6aa-7cdfe869b740.png> 
Some commands are highlighted, others are not. Do you have an explanation for that? Or is there a setting that I forgot to activate?

**Comment by fredlcore** [comment]
Thanks!

**Comment by CycoPH** [comment]
What file extension are you using?
Also what language does VSCode identify the code as?
Here is what the code looks like when I save it as a .asm file with the Language Mode set to "6502 Assembly (atasm)"

![Capture](https://user-images.githubusercontent.com/2360950/185621517-49f3520f-acbe-473e-bfd0-0e5dfdc90a5f.JPG)

![image](https://user-images.githubusercontent.com/2360950/185621634-7d8adae7-e6a4-4bbb-8335-0ac12957ae5b.png)

**Comment by fredlcore** [comment]
Sorry for the missing feedback, it worked after changing it from Assembly to 6502 Assembly :)!
